import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import Navbar from "@/components/ui/Navbar";
import IntroSection from "@/sections/IntroSection";
import Link from "next/link";
import { GITHUB_URL, LINKED_IN_URL } from "@/lib/social-media-links";
import { Button } from "@/components/ui/button";
import SocialMediaRow from "@/components/ui/SocialMediaRow";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="h-full">
      <body className="dark antialiased flex py-[6rem] px-[10rem] h-full justify-center w-full">
        <div className="flex flex-col gap-[4rem] w-[50%] max-w-[40rem]">
          <IntroSection />
          <Navbar />

          <div className="flex-grow" />
          <SocialMediaRow />
        </div>

        <div className="w-[50%] max-w-[40rem]">{children}</div>
      </body>
    </html>
  );
}
