import type { Metadata } from "next";
import "./globals.css";
import Navbar from "@/components/ui/Navbar";
import SocialMediaRow from "@/components/ui/SocialMediaRow";
import { Inter } from "next/font/google";
import IntroCard from "@/sections/IntroCard";

const inter = Inter({
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="h-full">
      <body
        className={`${inter} dark antialiased flex py-[6rem] px-[10rem] h-full justify-center w-full`}
      >
        <div className=" w-[50%] max-w-[40rem] relative">
          <div className="flex flex-col gap-[4rem] fixed">
            <IntroCard />
            <Navbar />

            <div className="flex-grow" />
            <SocialMediaRow />
          </div>
        </div>

        <div className="w-[50%] max-w-[40rem]">{children}</div>
      </body>
    </html>
  );
}
